services:
  mergeprinall:
    image: ghcr.io/yanorei32/merge-pr-in-all:0.1.6
    hostname: mergeprinall
    container_name: mergeprinall__mergeprinall
    restart: unless-stopped

    environment:
      LOGIN: yanorei32
      TOKEN: ${TOKEN}
      LISTEN: 0.0.0.0:3000
      AUTH_TOKEN: ${AUTH_TOKEN}

    command: /usr/bin/merge-pr-in-all

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.8.2@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    hostname: cloudflared
    container_name: mergeprinall__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: mergeprinall__default
